import x from "@/assets/Eth logo.svg";
import y from "@/assets/tether-seeklogo.com 2.svg";
export const demoPoolData = [
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },

  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
];
