import x from "@/assets/Eth logo.svg";
import y from "@/assets/tether-seeklogo.com 2.svg";
export const demoPoolData = [
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0001",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },

  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0002",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0003",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0004",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0005",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0006",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0007",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0008",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,0009",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,011",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,210",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,130",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,014",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,200",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "10,400",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "20,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "12,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
  {
    assetXLogo: x,
    assetYLogo: y,
    assetXSymbol: "ETH",
    assetYSymbol: "USDT",
    TVL: "$26.3M",
    TokenX: "11,000",
    TokenY: "200",
    TradingVolumes: "$16.90",
    DebtRatio: "10%",
    NitroPointsGenerated: "10000 NP",
  },
];
