import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { TvlChart, VolumeChart } from "@/components/charts";
import { Pool } from "@/components/pools";
import { MobileMenu, Navbar } from "@/components/Navbar";
import { BorrowBase } from "@/components/borrow";
import { useMobileNavState } from "@/hooks/stores/mobileMenuStore";
import { useBorrowState } from "@/hooks/stores/borrowstores";
import { useSuccessState } from "@/hooks/stores/successStore";
import UpdateManager from "@/components/helper/UpdateManager";
const inter = Inter({ subsets: ["latin"] });

export default function Borrow() {
  const { isMobileMenuOpen }: any = useMobileNavState();
  const { isPreview }: any = useBorrowState();
  const { isSuccessfull }: any = useSuccessState();
  return (
    <>
      <Head>
        <title>Nitro finance || Liquidity Positions </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          isPreview || isSuccessfull
            ? `flex h-screen flex-col items-center justify-between  bg-background`
            : `flex min-h-screen flex-col items-center justify-between  bg-background`
        }
      >
        <UpdateManager />{" "}
        {isMobileMenuOpen ? (
          <MobileMenu />
        ) : (
          <>
            <Navbar />
            <BorrowBase />
          </>
        )}
      </main>
    </>
  );
}
