import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { Navbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nitro finance || Pools </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`flex min-h-screen flex-col items-center justify-between  bg-background`}
      >
        <Navbar />
      </main>
    </>
  );
}
