import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import { TvlChart, VolumeChart } from "@/components/charts";
import { Pool } from "@/components/pools";
import { MobileMenu, Navbar } from "@/components/Navbar";
import { LiquidityBase } from "@/components/liquidity";
import { useMobileNavState } from "@/hooks/stores/mobileMenuStore";
import UpdateManager from "@/components/helper/UpdateManager";
import { useAddLiquidityPreviewState } from "@/hooks/stores/addLiquidityStore";
import { useSuccessState } from "@/hooks/stores/successStore";
const inter = Inter({ subsets: ["latin"] });

export default function Liquidity() {
  const { isMobileMenuOpen }: any = useMobileNavState();
  const { isPreviewPositionAdd, isPreviewPositionRemove }: any =
    useAddLiquidityPreviewState();
  const { isSuccessfull }: any = useSuccessState();
  return (
    <>
      <Head>
        <title>Nitro finance || Pools </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={
          isPreviewPositionAdd || isPreviewPositionRemove || isSuccessfull
            ? `flex min-h-screen flex-col items-center justify-between  bg-background h-screen overflow-y-hidden`
            : "flex min-h-screen flex-col items-center justify-between  bg-background "
        }
      >
        <UpdateManager />{" "}
        {isMobileMenuOpen ? (
          <MobileMenu />
        ) : (
          <>
            <Navbar />
            <LiquidityBase />
            <div className="mb-20"></div>
          </>
        )}
      </main>
    </>
  );
}
